---
title: "Investigate Univariate Spatial Contexture"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.figure {
   margin-top: 10px;
   margin-bottom: 25px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

<style>
div.blue { background-color:#0099CC; border-radius: 5px; padding: 20px; font-size: 38px}
</style>
<div class = "blue">

<span style="color: white;">Univariate Ripley's K</span>

</div>
<br>

```{r library}
library(tidyverse)
library(targets)
library(ggplot2)
library(gtsummary)

theme_gtsummary_compact()
theme_set(theme_classic())
```

```{r load data}
markers_clinical <- read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/summarized_markers_clinical_ROI_04132023.rds")
markers_clinical <- markers_clinical %>% 
  # Subset to K99R00 patiants
  drop_na(pair_id) %>% 
  group_by(pair_id) %>% 
  mutate(have_a_match = dense_rank(interaction(suid, pair_id))) %>% 
  group_by(pair_id) %>% 
  mutate(is_paired = max(have_a_match)) %>% 
  filter(is_paired == 2) %>% 
  select(pair_id, everything(), -c(is_paired, have_a_match)) %>% 
  ungroup()

rois_clinical <- read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/long_format_markers_clinical_ROI_04132023.rds") %>% 
  select(suid, data_version, everything()) %>% 
  filter(suid %in% c(markers_clinical$suid))

KNN_ROI1_overall_univariate <- 
  read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/knn_ROI1_overall_univariate.rds")

C_ROI1_overall_univariate <- 
  read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/c_ROI1_overall_univariate.rds")
```

```{r subset K99R00}
KNN_ROI1_overall_univariate3 <- KNN_ROI1_overall_univariate %>% 
  inner_join(., rois_clinical %>% 
               select(image_tag, annotation, slide_type, site),
            by= c("image_tag")) # %>% 
  # filter(image_tag %in% c(rois_clinical$image_tag)) ########## Fix ids for the patients missing a 1

C_ROI1_overall_univariate <- C_ROI1_overall_univariate %>% 
  inner_join(., rois_clinical %>% 
               select(image_tag, annotation, slide_type, site),
            by= c("image_tag")) # %>% 
  # filter(image_tag %in% c(rois_clinical$image_tag)) 
```

# Data control - ICC
Here for KNN
```{r}
df_overall <- KNN_ROI1_overall_univariate3 %>% 
  filter(r == 50 & marker != "DAPI (DAPI) Positive") %>% 
  select(-r) %>% 
  as.data.frame()
df_intra <- df_overall %>% 
  filter(annotation == "Intratumoral")
df_peri <- df_overall %>% 
  filter(annotation == "Peripheral")


library(psych)
vec_col <- c("theoretical_csr", "permuted_csr", "observed",
             "degree_of_clustering_theoretical", "degree_of_clustering_permutation")
# ICCC_data <- data.frame(matrix(nrow = 1, ncol = 0))
ICC_data <- data.frame(matrix(nrow = 1, ncol = 0))
lb_data <- data.frame(matrix(nrow = 1, ncol = 0))
up_data <- data.frame(matrix(nrow = 1, ncol = 0))
fct_icc <- function(data, cell_type) {
  for (i in vec_col) {
    raw_df <- data %>% select(suid, marker)
    
    if (class(data[, i]) == "numeric" |
        class(data[, i]) == "integer") {
      ICC_df <- cbind(raw_df, value = data[, i]) %>%
        drop_na() %>%
        filter(marker == cell_type)
      ICC_df <- ICC_df %>%
        mutate(Slide = "Slide0") %>%
        group_by(suid) %>%
        mutate(n = row_number(suid)) %>%
        ungroup() %>%
        unite(slide_id, Slide:n, sep = "", remove = TRUE, na.rm = TRUE) %>%
        pivot_wider(id_cols = -c(marker),
                    names_from = slide_id, values_from = value) %>%
        select(c(starts_with("slide")))
      
      ICC <- ICC(ICC_df)$results[4, 2]
      ICC_data <- cbind(ICC_data, ICC)
      ICC <- ICC(ICC_df)$results[4, 7]
      lb_data <- cbind(lb_data, ICC)
      ICC <- ICC(ICC_df)$results[4, 8]
      up_data <- cbind(up_data, ICC)
      
    }
  }
  ICCC_data <- bind_rows(ICC_data, lb_data, up_data)
  colnames(ICCC_data) <- vec_col
  ICCC_data <- as.data.frame(t(ICCC_data)) %>%
    mutate(ICC_lb_up = 
             paste(round(V1, 2), " (", 
                   round(V2, 2), ", ", 
                   round(V3, 2), ")", sep = "")) %>%
    select(ICC_lb_up)
}

vec_mar <- c(unique(df_overall$marker))
ICC_lb_up_df_a <- data.frame(matrix(nrow = 1, ncol = 0))
ICC_lb_up_df_b <- data.frame(matrix(nrow = 1, ncol = 0))
ICC_lb_up_df_c <- data.frame(matrix(nrow = 1, ncol = 0))
for (i in vec_mar) {
  a <- fct_icc(df_overall, cell_type = i) %>% 
    `colnames<-`(i)
  ICC_lb_up_df_a <- cbind(ICC_lb_up_df_a, a) %>% 
    mutate(annotation = "Overall", .before= 1)
  b <- fct_icc(df_intra, cell_type = i) %>% 
    `colnames<-`(i)
  ICC_lb_up_df_b <- cbind(ICC_lb_up_df_b, b) %>% 
    mutate(annotation = "Intratumoral")
  c <- fct_icc(df_peri, cell_type = i) %>% 
    `colnames<-`(i)
  ICC_lb_up_df_c <- cbind(ICC_lb_up_df_c, c) %>% 
    mutate(annotation = "Peripheral")
  
}
bind_rows(ICC_lb_up_df_a,
          ICC_lb_up_df_b,
          ICC_lb_up_df_c)

rm(ICC_data, lb_data, up_data, a, b, c,
   ICC_lb_up_df_a, ICC_lb_up_df_b, ICC_lb_up_df_c,
   df_overall, df_intra, df_peri)
```

# Explore data

```{r}
KNN_ROI1_overall_univariate4 <- KNN_ROI1_overall_univariate3 %>% 
  filter(r == 50) %>% 
  group_by(suid, marker, annotation) %>% 
  summarize(theoretical_csr = mean(theoretical_csr, na.rm=TRUE),
            permuted_csr = mean(permuted_csr, na.rm=TRUE),
            observed = mean(observed, na.rm=TRUE),
            degree_of_clustering_permutation = mean(degree_of_clustering_permutation, na.rm=TRUE),
            degree_of_clustering_theoretical = mean(degree_of_clustering_theoretical, na.rm=TRUE)) %>% 
  ungroup() %>% 
  distinct(suid, marker, annotation, .keep_all = TRUE) %>% 
  mutate(across(where(is.numeric), ~ na_if(., NaN)))

KNN_ROI1_overall_univariate_intra <- KNN_ROI1_overall_univariate4 %>% 
  filter(annotation == "Intratumoral") %>% 
  select(-annotation)
KNN_ROI1_overall_univariate_peri <- KNN_ROI1_overall_univariate4 %>% 
  filter(annotation == "Peripheral") %>% 
  select(-annotation)

KNN_ROI1_overall_univariate4 <- 
  full_join(KNN_ROI1_overall_univariate_intra, 
            KNN_ROI1_overall_univariate_peri,
            by= c("suid", "marker"),
            suffix = c("_i", "_p"))


########################################################################### IV ### Data exploratory
# Why do we see so little cells CD3, it should be more than CD11

is.na(KNN_ROI1_overall_univariate4$degree_of_clustering_permutation_i)

KNN_ROI1_overall_univariate4 %>% 
  ggplot(aes(x= marker, y= theoretical_csr_i, color= marker))+
  geom_boxplot()+
  theme_classic()+
  coord_flip()+ 
  theme(legend.position = "none")

KNN_ROI1_overall_univariate4 %>% 
  ggplot(aes(x= marker, y= degree_of_clustering_permutation_i, color= marker))+
  geom_violin()+
  theme_classic()+
  coord_flip()+ 
  theme(legend.position = "none")

```

# Add Abundance Categories / Spatial Categories

```{r add abundance cat}
abundance_cat  <- readRDS("~/Documents/GitHub/Peres/spatial_contexture/summarized_markers_clinical_ROI_04132023.rds") %>% 
  mutate(vitalstatus = case_when(
    vitalstatus == "Deceased"                ~ 1,
    vitalstatus == "Alive"                   ~ 0
  )) %>% 
  select(suid, 
         vitalstatus, timelastfu,
         refage, race, stage, 
         cd3_tumor_i : immunoscore_2018lancet_patients)
```

```{r create spatial cat, fig.width=12, fig.height=10}
KNN_ROI1_overall_univariate5 <- KNN_ROI1_overall_univariate4 %>% 
  full_join(., abundance_cat, 
            by = "suid")

KNN_ROI1_overall_univariate6 <- KNN_ROI1_overall_univariate5 %>% 
  filter(marker == "CD11b (Opal 620) Positive") %>% 
  mutate(spat_CD11_i = case_when(
    cd11b_total_i == "Absence"                            ~ "Absence",
    ntile(theoretical_csr_i, 2) == 1       ~ "Low",
    ntile(theoretical_csr_i, 2) == 2       ~ "High",
  ), spat_CD11_i = factor(spat_CD11_i, levels = c("Absence", "Low","High"))) %>% 
  select(suid, marker, spat_CD11_i)

KNN_ROI1_overall_univariate7 <- KNN_ROI1_overall_univariate5 %>% 
  filter(marker == "CD3 (Opal 650) Positive") %>% 
  mutate(tertile = ntile(theoretical_csr_i, 2)) %>% 
  mutate(spat_CD3_i = case_when(
    tertile == 1                                          ~ "Low",
    tertile == 2                                          ~ "High"
  ), spat_CD3_i = factor(spat_CD3_i, levels = c("Low","High"))) %>% 
  select(suid, marker, spat_CD3_i)

KNN_ROI1_overall_univariate_final <- KNN_ROI1_overall_univariate5 %>% 
  full_join(KNN_ROI1_overall_univariate6, ., 
            by= c("suid", "marker")) %>% 
  full_join(KNN_ROI1_overall_univariate7, .,
            by= c("suid", "marker"))
```


```{r ggridge, fig.width=12, fig.height=10}
library(ggridges)
KNN_ROI1_overall_univariate_final %>% 
  select(spat_CD3_i, marker, theoretical_csr_i) %>% 

  mutate(location = "Tumor") %>% 

  ggplot(aes(y=spat_CD3_i, x=theoretical_csr_i,  fill=marker#, linetype = location
             )) +
  geom_density_ridges(alpha=0.5) +
  ggtitle("Intratumoral")+
  theme_ridges()+ facet_wrap(.~ marker, ncol = 2)
```

```{r}
library(survival)

tbl1 <- KNN_ROI1_overall_univariate_final %>% 
  select(vitalstatus, timelastfu,
         spat_CD11_i,
         refage, race, stage) %>%
  tbl_uvregression(method = survival::coxph,
                   y = (Surv(time = KNN_ROI1_overall_univariate_final$timelastfu,
                             event = KNN_ROI1_overall_univariate_final$vitalstatus)),
                   exponentiate = TRUE) %>%
  bold_labels() %>% italicize_levels() %>%
  bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl2 <-
  coxph(Surv(time = KNN_ROI1_overall_univariate_final$timelastfu,
             event = KNN_ROI1_overall_univariate_final$vitalstatus) ~
          spat_CD11_i + refage + stage,
        data =  KNN_ROI1_overall_univariate_final) %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")
tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))

tbl1 <- KNN_ROI1_overall_univariate_final %>% 
  select(vitalstatus, timelastfu,
         spat_CD3_i,
         refage, race, stage) %>%
  tbl_uvregression(method = survival::coxph,
                   y = (Surv(time = KNN_ROI1_overall_univariate_final$timelastfu,
                             event = KNN_ROI1_overall_univariate_final$vitalstatus)),
                   exponentiate = TRUE) %>%
  bold_labels() %>% italicize_levels() %>%
  bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
tbl2 <-
  coxph(Surv(time = KNN_ROI1_overall_univariate_final$timelastfu,
             event = KNN_ROI1_overall_univariate_final$vitalstatus) ~
          spat_CD3_i + refage + stage,
        data =  KNN_ROI1_overall_univariate_final) %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")
tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))

```








<!-- # Study population - Patient characteristics -->

<!-- # Immune cell spatial's distribution -->
<!-- ```{r} -->
<!-- bivariate_k %>%  -->
<!--   tbl_summary -->

<!-- ``` -->











