---
title: "Investigate Ripley in Univariate Spatial Contexture - radius 125"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.figure {
   margin-top: 10px;
   margin-bottom: 25px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

<style>
div.blue { background-color:#0099CC; border-radius: 5px; padding: 20px; font-size: 38px}
</style>
<div class = "blue">

<span style="color: white;">Univariate Ripley's K</span>

</div>
<br>

```{r library}
library(tidyverse)
library(targets)
library(ggplot2)
library(gtsummary)

theme_gtsummary_compact()
theme_set(theme_classic())
```

```{r load data}
markers_clinical <- read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/summarized_markers_clinical_ROI_04132023.rds")
markers_clinical <- markers_clinical %>% 
  # Subset to K99R00 patiants
  drop_na(pair_id) %>% 
  group_by(pair_id) %>% 
  mutate(have_a_match = dense_rank(interaction(suid, pair_id))) %>% 
  group_by(pair_id) %>% 
  mutate(is_paired = max(have_a_match)) %>% 
  filter(is_paired == 2) %>% 
  select(pair_id, everything(), -c(is_paired, have_a_match)) %>% 
  ungroup()

rois_clinical <- read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/long_format_markers_clinical_ROI_04132023.rds") %>% 
  select(suid, data_version, everything()) %>% 
  filter(suid %in% c(markers_clinical$suid))

# gdistance_ROI1_overall_univariate <- 
#   read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/knn_ROI1_overall_univariate.rds")

ripley_ROI1_overall_univariate <- 
  read_rds("/Users/colinccm/Documents/GitHub/Peres/spatial_contexture/c_ROI1_overall_univariate.rds")
```

```{r subset K99R00}
ripley_ROI1_overall_univariate3 <- ripley_ROI1_overall_univariate %>% 
  inner_join(., rois_clinical %>% 
               select(image_tag, annotation, slide_type, site),
            by= c("image_tag")) # %>% 
  # filter(image_tag %in% c(rois_clinical$image_tag)) ########## Fix ids for the patients missing a 1
```

We use a radius of 125 and look for T cell markers
```{r radius filter}
ripley_ROI1_overall_univariate3 <- ripley_ROI1_overall_univariate3 %>% 
  filter(r == 125 & marker != "DAPI (DAPI) Positive") %>% 
  select(-r)
```

```{r marker cleanup}
ripley_ROI1_overall_univariate3 <- ripley_ROI1_overall_univariate3 %>%
  mutate(marker = str_remove(marker, "(\\(.*\\) )"),
         marker = str_replace(marker, " Positive", "+")) %>% 
  filter(marker %in% c("CD3+", "CD3+ CD8+", "CD3+ FOXP3+",
                       "FOXP3+", "CD8+"))
```



# Data control - ICC
Here for Ripley's K
```{r}
df_overall <- ripley_ROI1_overall_univariate3 %>% 
  as.data.frame()
df_intra <- df_overall %>% 
  filter(annotation == "Intratumoral")
df_peri <- df_overall %>% 
  filter(annotation == "Peripheral")


library(psych)
vec_col <- c(#"theoretical_csr", "permuted_csr", "observed",
             # "degree_of_clustering_theoretical", 
             "degree_of_clustering_permutation")
# ICCC_data <- data.frame(matrix(nrow = 1, ncol = 0))
ICC_data <- data.frame(matrix(nrow = 1, ncol = 0))
lb_data <- data.frame(matrix(nrow = 1, ncol = 0))
up_data <- data.frame(matrix(nrow = 1, ncol = 0))
fct_icc <- function(data, cell_type) {
  for (i in vec_col) {
    raw_df <- data %>% select(suid, marker)
    
    if (class(data[, i]) == "numeric" |
        class(data[, i]) == "integer") {
      ICC_df <- cbind(raw_df, value = data[, i]) %>%
        drop_na() %>%
        filter(marker == cell_type)
      ICC_df <- ICC_df %>%
        mutate(Slide = "Slide0") %>%
        group_by(suid) %>%
        mutate(n = row_number(suid)) %>%
        ungroup() %>%
        unite(slide_id, Slide:n, sep = "", remove = TRUE, na.rm = TRUE) %>%
        pivot_wider(id_cols = -c(marker),
                    names_from = slide_id, values_from = value) %>%
        select(c(starts_with("slide")))
      
      ICC <- ICC(ICC_df)$results[4, 2]
      ICC_data <- cbind(ICC_data, ICC)
      ICC <- ICC(ICC_df)$results[4, 7]
      lb_data <- cbind(lb_data, ICC)
      ICC <- ICC(ICC_df)$results[4, 8]
      up_data <- cbind(up_data, ICC)
      
    }
  }
  ICCC_data <- bind_rows(ICC_data, lb_data, up_data)
  colnames(ICCC_data) <- vec_col
  ICCC_data <- as.data.frame(t(ICCC_data)) %>%
    mutate(ICC_lb_up = 
             paste(round(V1, 2), " (", 
                   round(V2, 2), ", ", 
                   round(V3, 2), ")", sep = "")) %>%
    select(ICC_lb_up)
}

vec_mar <- c(unique(df_overall$marker))
ICC_lb_up_df_a <- data.frame(matrix(nrow = 1, ncol = 0))
ICC_lb_up_df_b <- data.frame(matrix(nrow = 1, ncol = 0))
ICC_lb_up_df_c <- data.frame(matrix(nrow = 1, ncol = 0))
for (i in vec_mar) {
  a <- fct_icc(df_overall, cell_type = i) %>% 
    `colnames<-`(i)
  ICC_lb_up_df_a <- cbind(ICC_lb_up_df_a, a) %>% 
    mutate(annotation = "Overall", .before= 1)
  b <- fct_icc(df_intra, cell_type = i) %>% 
    `colnames<-`(i)
  ICC_lb_up_df_b <- cbind(ICC_lb_up_df_b, b) %>% 
    mutate(annotation = "Intratumoral")
  c <- fct_icc(df_peri, cell_type = i) %>% 
    `colnames<-`(i)
  ICC_lb_up_df_c <- cbind(ICC_lb_up_df_c, c) %>% 
    mutate(annotation = "Peripheral")
  
}
ICC_data <- bind_rows(ICC_lb_up_df_a,
          ICC_lb_up_df_b,
          ICC_lb_up_df_c)
ICC_data

rm(ICC_data, lb_data, up_data, a, b, c,
   ICC_lb_up_df_a, ICC_lb_up_df_b, ICC_lb_up_df_c,
   df_overall, df_intra, df_peri)
```

# Explore data

```{r summarize data}
ripley_ROI1_overall_univariate4 <- ripley_ROI1_overall_univariate3 %>% 
  group_by(suid, marker, annotation) %>% 
  summarize(theoretical_csr = mean(theoretical_csr, na.rm=TRUE),
            permuted_k = mean(permuted_k, na.rm=TRUE),
            observed_k = mean(observed_k, na.rm=TRUE),
            degree_of_clustering_permutation = mean(degree_of_clustering_permutation, na.rm=TRUE),
            degree_of_clustering_theoretical = mean(degree_of_clustering_theoretical, na.rm=TRUE)) %>% 
  ungroup() %>% 
  distinct(suid, marker, annotation, .keep_all = TRUE) %>% 
  mutate(across(where(is.numeric), ~ na_if(., NaN)))

ripley_ROI1_overall_univariate_intra <- ripley_ROI1_overall_univariate4 %>% 
  filter(annotation == "Intratumoral") %>% 
  select(-annotation)
ripley_ROI1_overall_univariate_peri <- ripley_ROI1_overall_univariate4 %>% 
  filter(annotation == "Peripheral") %>% 
  select(-annotation)

ripley_ROI1_overall_univariate5 <- 
  full_join(ripley_ROI1_overall_univariate_intra, 
            ripley_ROI1_overall_univariate_peri,
            by= c("suid", "marker"),
            suffix = c("_i", "_p"))
```


```{r explore summarize data}
ripley_ROI1_overall_univariate4 %>% 
  ggplot(aes(x= marker, y= degree_of_clustering_permutation, color= marker))+
  geom_boxplot()+
  theme_classic()+
  coord_flip()+ 
  theme(legend.position = "none")+ 
  facet_wrap(. ~ annotation)

ripley_ROI1_overall_univariate4 %>% 
  ggplot(aes(x= marker, y= degree_of_clustering_permutation, color= marker))+
  geom_violin()+
  theme_classic()+
  coord_flip()+ 
  theme(legend.position = "none")+ 
  facet_wrap(. ~ annotation)

tbl1 <- ripley_ROI1_overall_univariate4 %>% 
  filter(marker == "CD3+") %>% 
  select("CD3+" = degree_of_clustering_permutation, annotation) %>% 
  tbl_summary(by= annotation) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(t= .05) %>% add_overall() %>% 
  modify_header(label = "**degree of clustering permutation**") %>%
  modify_caption("**degree of clustering permutation** (N = {N})")
tbl2 <- ripley_ROI1_overall_univariate4 %>% 
  filter(marker == "CD8+") %>% 
  select("CD8+" = degree_of_clustering_permutation, annotation) %>% 
  tbl_summary(by= annotation) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(t= .05) %>% add_overall()
tbl3 <- ripley_ROI1_overall_univariate4 %>% 
  filter(marker == "CD3+ CD8+") %>% 
  select("CD3+ CD8+" = degree_of_clustering_permutation, annotation) %>% 
  tbl_summary(by= annotation) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(t= .05) %>% add_overall()
tbl4 <- ripley_ROI1_overall_univariate4 %>% 
  filter(marker == "FOXP3+") %>% 
  select("FOXP3+" = degree_of_clustering_permutation, annotation) %>% 
  tbl_summary(by= annotation) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(t= .05) %>% add_overall()
tbl5 <- ripley_ROI1_overall_univariate4 %>% 
  filter(marker == "CD3+ FOXP3+") %>% 
  select("CD3+ FOXP3+" = degree_of_clustering_permutation, annotation) %>% 
  tbl_summary(by= annotation) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(t= .05) %>% add_overall()
tbl_stack(list(tbl1, tbl2, tbl3, tbl4, tbl5))
```

# Add Abundance Categories / Spatial Categories

```{r load abundance }
abundance_cat <- markers_clinical

abundance_cat1 <- abundance_cat %>% 
  
  mutate(cd3_tumor.i = case_when(
    tumor_percent_cd3_i <= 1      ~ "low",
    tumor_percent_cd3_i > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_cd8plus_tumor.i = case_when(
    tumor_percent_cd3plus_cd8plus_i <= 1      ~ "low",
    tumor_percent_cd3plus_cd8plus_i > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_foxp3plus_tumor.i = case_when(
    tumor_percent_cd3plus_foxp3plus_i <= 1      ~ "low",
    tumor_percent_cd3plus_foxp3plus_i > 1       ~ "high"
  )) %>% 
  mutate(cd11b_tumor.i = case_when(
    tumor_percent_cd11b_i == 0      ~ "Absence",
    tumor_percent_cd11b_i > 0       ~ "Presence"
  )) %>% 
  mutate(cd11bplus_cd15plus_tumor.i = case_when(
    tumor_percent_cd11bplus_cd15plus_i == 0      ~ "Absence",
    tumor_percent_cd11bplus_cd15plus_i > 0       ~ "Presence"
  )) %>% 
  
  mutate(cd3_stroma.i = case_when(
    stroma_percent_cd3_i <= 1      ~ "low",
    stroma_percent_cd3_i > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_cd8plus_stroma.i = case_when(
    stroma_percent_cd3plus_cd8plus_i <= 1      ~ "low",
    stroma_percent_cd3plus_cd8plus_i > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_foxp3plus_stroma.i = case_when(
    stroma_percent_cd3plus_foxp3plus_i <= 1      ~ "low",
    stroma_percent_cd3plus_foxp3plus_i > 1       ~ "high"
  )) %>% 
  mutate(CD11b_stroma.i = case_when(
    stroma_percent_cd11b_i == 0      ~ "Absence",
    stroma_percent_cd11b_i > 0       ~ "Presence"
  )) %>%
  mutate(cd11bplus_cd15plus_stroma.i = case_when(
    stroma_percent_cd11bplus_cd15plus_i == 0      ~ "Absence",
    stroma_percent_cd11bplus_cd15plus_i > 0       ~ "Presence"
  )) %>% 
  
  mutate(cd3_total.i = case_when(
    total_percent_cd3_i <= 1      ~ "low",
    total_percent_cd3_i > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_cd8plus_total.i = case_when(
    total_percent_cd3plus_cd8plus_i <= 1      ~ "low",
    total_percent_cd3plus_cd8plus_i > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_foxp3plus_total.i = case_when(
    total_percent_cd3plus_foxp3plus_i <= 1      ~ "low",
    total_percent_cd3plus_foxp3plus_i > 1       ~ "high"
  )) %>% 
  mutate(cd11b_total.i = case_when(
    total_percent_cd11b_i == 0      ~ "Absence",
    total_percent_cd11b_i > 0       ~ "Presence"
  )) %>% 
  mutate(cd11bplus_cd15plus_total.i = case_when(
    total_percent_cd11bplus_cd15plus_i == 0      ~ "Absence",
    total_percent_cd11bplus_cd15plus_i > 0       ~ "Presence"
  )) %>% 
  
  
  
  mutate(cd3_tumor.p = case_when(
    tumor_percent_cd3_p <= 1      ~ "low",
    tumor_percent_cd3_p > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_cd8plus_tumor.p = case_when(
    tumor_percent_cd3plus_cd8plus_p <= 1      ~ "low",
    tumor_percent_cd3plus_cd8plus_p > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_foxp3plus_tumor.p = case_when(
    tumor_percent_cd3plus_foxp3plus_p <= 1      ~ "low",
    tumor_percent_cd3plus_foxp3plus_p > 1       ~ "high"
  )) %>% 
  mutate(cd11b_tumor.p = case_when(
    tumor_percent_cd11b_p == 0      ~ "Absence",
    tumor_percent_cd11b_p > 0       ~ "Presence"
  )) %>% 
  mutate(cd11bplus_cd15plus_tumor.p = case_when(
    tumor_percent_cd11bplus_cd15plus_p == 0      ~ "Absence",
    tumor_percent_cd11bplus_cd15plus_p > 0       ~ "Presence"
  )) %>% 
  
  mutate(cd3_stroma.p = case_when(
    stroma_percent_cd3_p <= 1      ~ "low",
    stroma_percent_cd3_p > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_cd8plus_stroma.p = case_when(
    stroma_percent_cd3plus_cd8plus_p <= 1      ~ "low",
    stroma_percent_cd3plus_cd8plus_p > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_foxp3plus_stroma.p = case_when(
    stroma_percent_cd3plus_foxp3plus_p <= 1      ~ "low",
    stroma_percent_cd3plus_foxp3plus_p > 1       ~ "high"
  )) %>% 
  mutate(CD11b_stroma.p = case_when(
    stroma_percent_cd11b_p == 0      ~ "Absence",
    stroma_percent_cd11b_p > 0       ~ "Presence"
  )) %>% 
  mutate(cd11bplus_cd15plus_stroma.p = case_when(
    stroma_percent_cd11bplus_cd15plus_p == 0      ~ "Absence",
    stroma_percent_cd11bplus_cd15plus_p > 0       ~ "Presence"
  )) %>% 
    
  mutate(cd3_total.p = case_when(
    total_percent_cd3_p <= 1      ~ "low",
    total_percent_cd3_p > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_cd8plus_total.p = case_when(
    total_percent_cd3plus_cd8plus_p <= 1      ~ "low",
    total_percent_cd3plus_cd8plus_p > 1       ~ "high"
  )) %>% 
  mutate(cd3plus_foxp3plus_total.p = case_when(
    total_percent_cd3plus_foxp3plus_p <= 1      ~ "low",
    total_percent_cd3plus_foxp3plus_p > 1       ~ "high"
  )) %>% 
  mutate(cd11b_total.p = case_when(
    total_percent_cd11b_p == 0      ~ "Absence",
    total_percent_cd11b_p > 0       ~ "Presence"
  )) %>% 
  mutate(cd11bplus_cd15plus_total.p = case_when(
    total_percent_cd11bplus_cd15plus_p == 0      ~ "Absence",
    total_percent_cd11bplus_cd15plus_p > 0       ~ "Presence"
  )) %>% 
  
  mutate(across(c(ends_with(".p") & contains("cd3"), 
                  ends_with(".i") & contains("cd3")
                  ), ~ factor(., levels = c("low","high"))
                ))


```


```{r add abundance cat}
abundance_cat <- abundance_cat1 %>% 
  pivot_longer(cols = c(contains("total.i"), contains("total.p")), 
               names_to = "abundance_cat",
               values_to = "abundance_value") %>% 
  mutate(annotation = case_when(
    str_detect(abundance_cat, ".i")      ~ "Intratumoral",
    str_detect(abundance_cat, ".p")      ~ "Peripheral"
  )) %>% 
  mutate(marker = case_when(
    str_detect(abundance_cat, "cd3plus_cd8plus")      ~ "CD3+ CD8+",
    str_detect(abundance_cat, "cd3plus_foxp3plus")    ~ "CD3+ FOXP3+",
    str_detect(abundance_cat, "cd3_")                 ~ "CD3+"
  ))

```

```{r create spatial cat}
# ripley_ROI1_overall_univariate5 <- ripley_ROI1_overall_univariate5 %>% 
#   full_join(., abundance_cat, 
#             by = "suid")

ripley_ROI1_overall_univariate6 <- ripley_ROI1_overall_univariate4 %>% 
  left_join(., abundance_cat,
            by = c("suid", "annotation", "marker"))

# ripley_ROI1_overall_univariate6 <- ripley_ROI1_overall_univariate5 %>% 
#   filter(marker == "CD11b (Opal 620) Positive") %>% 
#   mutate(spat_CD11_i = case_when(
#     cd11b_total_i == "Absence"                            ~ "Absence",
#     ntile(theoretical_csr_i, 2) == 1       ~ "Low",
#     ntile(theoretical_csr_i, 2) == 2       ~ "High",
#   ), spat_CD11_i = factor(spat_CD11_i, levels = c("Absence", "Low","High"))) %>% 
#   select(suid, marker, spat_CD11_i)

ripley_ROI1_overall_univariate7 <- ripley_ROI1_overall_univariate6 %>% 
  # select(suid, marker, annotation, degree_of_clustering_permutation, refage) %>% 
  group_by(marker, annotation) %>% 
  mutate(tertile = ntile(degree_of_clustering_permutation, 2)) %>% 
  # mutate(med_per = median(degree_of_clustering_permutation, na.rm = TRUE))
  mutate(spatial_cat = case_when(
    tertile == 1                                          ~ "Low",
    tertile == 2                                          ~ "High",
    is.na(degree_of_clustering_permutation)               ~ "Absence"
  ), spatial_cat = factor(spatial_cat, levels = c("Low","High", "Absence"))) %>% 
  mutate(abundance_spatial_cat = case_when(
    spatial_cat == "Low" &
      abundance_value == "low"                            ~ "Low/low",
    spatial_cat == "Low" &
      abundance_value == "high"                           ~ "Low/high",
    spatial_cat == "High" &
      abundance_value == "low"                            ~ "High/low",
    spatial_cat == "High" &
      abundance_value == "high"                           ~ "High/high",
    spatial_cat == "Absence"                              ~ "Absence"
  )) %>% 
  ungroup()

ripley_ROI1_overall_univariate_final <- ripley_ROI1_overall_univariate7 #%>%
#   full_join(ripley_ROI1_overall_univariate6, ., 
#             by= c("suid", "marker")) %>% 
#   full_join(ripley_ROI1_overall_univariate7, .,
#             by= c("suid", "marker"))
```

# Explore categories

```{r}
tbl1 <- ripley_ROI1_overall_univariate_final %>% 
  filter(annotation == "Intratumoral") %>% 
  filter(marker == "CD3+") %>% 
  select(degree_of_clustering_permutation, refage, race, stage, vitalstatus, marker, spatial_cat, abundance_spatial_cat) %>% 
  tbl_summary(by= spatial_cat) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(.05) %>% add_overall() %>% 
  modify_header(label = "**CD3+ cat**") %>%
  modify_caption("**spatial_cat**")

tbl2 <- ripley_ROI1_overall_univariate_final %>% 
  filter(annotation == "Peripheral") %>% 
  filter(marker == "CD3+") %>% 
  select(degree_of_clustering_permutation, refage, race, stage, vitalstatus, marker, spatial_cat, abundance_spatial_cat) %>% 
  tbl_summary(by= spatial_cat) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(.05) %>% add_overall()
tbl_merge(list(tbl1, tbl2), tab_spanner = c("Intratumoral", "Peripheral"))

tbl1 <- ripley_ROI1_overall_univariate_final %>% 
  filter(annotation == "Intratumoral") %>% 
  filter(marker == "CD3+") %>% 
  select(degree_of_clustering_permutation, refage, race, stage, vitalstatus, marker, spatial_cat, abundance_spatial_cat) %>% 
  tbl_summary(by= abundance_spatial_cat) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(.05) %>% add_overall() %>% 
  modify_header(label = "**CD3+ cat**") %>%
  modify_caption("**abundance_spatial_cat**")

tbl2 <- ripley_ROI1_overall_univariate_final %>% 
  filter(annotation == "Peripheral") %>% 
  filter(marker == "CD3+") %>% 
  select(degree_of_clustering_permutation, refage, race, stage, vitalstatus, marker, spatial_cat, abundance_spatial_cat) %>% 
  tbl_summary(by= abundance_spatial_cat) %>% 
  bold_labels() %>% 
  add_p() %>% bold_p(.05) %>% add_overall()
tbl_merge(list(tbl1, tbl2), tab_spanner = c("Intratumoral", "Peripheral"))

ripley_ROI1_overall_univariate_final %>% 
  filter(marker == "CD3+") %>% 
  ggplot(aes(x= spatial_cat, y= degree_of_clustering_permutation, color= race))+
  geom_boxplot()+
  ggtitle("spatial_cat for CD3+")+
  facet_wrap(.~ annotation)

ripley_ROI1_overall_univariate_final %>% 
  filter(marker == "CD3+") %>% 
  ggplot(aes(x= abundance_spatial_cat, y= degree_of_clustering_permutation, color= race))+
  geom_boxplot()+
  ggtitle("abundance_spatial_cat for CD3+")+
  facet_wrap(.~ annotation)
```


```{r ggridge, fig.width=12, fig.height=10}
library(ggridges)
ripley_ROI1_overall_univariate_final %>% 
  select(spatial_cat, annotation, marker, degree_of_clustering_permutation) %>% 

  ggplot(aes(y=spatial_cat, x=degree_of_clustering_permutation,  fill=annotation, linetype = annotation
             )) +
  geom_density_ridges(alpha=0.5) +
  ggtitle("Overall")+
  theme_ridges()+ facet_wrap(annotation~ marker, ncol = 2)

ripley_ROI1_overall_univariate_final %>% 
  select(abundance_spatial_cat, annotation, marker, degree_of_clustering_permutation) %>% 

  ggplot(aes(y=abundance_spatial_cat, x=degree_of_clustering_permutation,  fill=abundance_spatial_cat, linetype = annotation
             )) +
  geom_density_ridges(alpha=0.5) +
  ggtitle("Overall meaning cat : spatial/abundance")+
  theme_ridges()+ facet_wrap(annotation~ marker, ncol = 2)
```

```{r}

```





```{r}
# library(survival)
# 
# tbl1 <- ripley_ROI1_overall_univariate_final %>% 
#   select(vitalstatus, timelastfu,
#          spat_CD11_i,
#          refage, race, stage) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = ripley_ROI1_overall_univariate_final$timelastfu,
#                              event = ripley_ROI1_overall_univariate_final$vitalstatus)),
#                    exponentiate = TRUE) %>%
#   bold_labels() %>% italicize_levels() %>%
#   bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
# tbl2 <-
#   coxph(Surv(time = ripley_ROI1_overall_univariate_final$timelastfu,
#              event = ripley_ROI1_overall_univariate_final$vitalstatus) ~
#           spat_CD11_i + refage + stage,
#         data =  ripley_ROI1_overall_univariate_final) %>%
#   tbl_regression(exponentiate = TRUE) %>%
#   bold_p(t = .05) %>%
#   add_nevent(location = "level") %>% add_n(location = "level")
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))
# 
# tbl1 <- ripley_ROI1_overall_univariate_final %>% 
#   select(vitalstatus, timelastfu,
#          spat_CD3_i,
#          refage, race, stage) %>%
#   tbl_uvregression(method = survival::coxph,
#                    y = (Surv(time = ripley_ROI1_overall_univariate_final$timelastfu,
#                              event = ripley_ROI1_overall_univariate_final$vitalstatus)),
#                    exponentiate = TRUE) %>%
#   bold_labels() %>% italicize_levels() %>%
#   bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
# tbl2 <-
#   coxph(Surv(time = ripley_ROI1_overall_univariate_final$timelastfu,
#              event = ripley_ROI1_overall_univariate_final$vitalstatus) ~
#           spat_CD3_i + refage + stage,
#         data =  ripley_ROI1_overall_univariate_final) %>%
#   tbl_regression(exponentiate = TRUE) %>%
#   bold_p(t = .05) %>%
#   add_nevent(location = "level") %>% add_n(location = "level")
# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Univariable**", "**Multivariable**"))

```












